---
title: "budget_by_energy_type_v_cc"
author: "Athena Zhang"
date: "2023-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(tidytext)
library(SnowballC)
library(ggwordcloud)
```

```{r}
epi <- read_csv('data/epi2022regionalresults05302022.csv')
d <- read.csv('data/ALL_COUNTRY.csv')
```

```{r}
# selecting relevant policy data
policy <- d |> 
  select('Country', 'Policy.Category', 'Name.of.policy', 'Energy.Type', 'Date.of.entry.info.force','Value.committed..USD')
```

```{r}
# removing NA for date of entry
policy$'Date.of.entry.info.force' <- na_if(policy$'Date.of.entry.info.force', "")
policy <- policy |>
  filter(!is.na(Date.of.entry.info.force))
```

```{r}
# remove 0 for value committed
policy <- policy |>
  filter(Value.committed..USD != 0)
```

```{r}
# keep 'clean conditional' and 'clean unconditional' policies
policy <- policy |>
  filter(Policy.Category %in% c('clean conditional', 'clean unconditional'))
```

```{r}
# selecting only country and climate change relevant measures
cc <- epi |>
  select(country, PCC.new)
```

```{r}
setdiff(policy$Country, cc$country) #in policy but not in cc
# recode countries in cc
cc <- cc |> mutate(country = recode(country,
                           "Netherlands" = "The Netherlands",
                           "United States of America" = "United States",
                           "Viet Nam" = "Vietnam",
                           "South Korea" = "Republic of Korea"))
```

```{r}
# remove 'European Institutions' from country in policy
policy <- policy |>
  filter(Country != 'European Institutions')
```

```{r}
# aggregating buget by energy type
policy_budget <- policy |> 
  group_by(Country, `Energy.Type`) |>
  summarise(total_budget = sum(`Value.committed..USD`))
```

```{r}
# pivoting table so energy type is the variable
policy_budget_pivoted <- policy_budget |>
  pivot_wider(
    id_cols = Country,
    names_from = `Energy.Type`,
    values_from = total_budget
  )
```

```{r}
# NA values to 0
policy_budget_pivoted[is.na(policy_budget_pivoted)] <- 0
```

```{r}
# rename budget:Country to country
policy_budget_pivoted <- rename(policy_budget_pivoted, country = Country)
```

```{r}
budget_cc <- left_join(policy_budget_pivoted, cc, by = "country")
```

## LASSO

```{r}
library(glmnet)
```

```{r}
#outcome variable = EPI
y <- budget_cc$PCC.new
#predictor variables = budget (by energy type)
x <- budget_cc |> select(`solar`:`oil and oil products`) |> as.matrix()
```

```{r}
model <- glmnet(x, y , lambda = 0.01, family = "gaussian", intercept = TRUE, alpha = 1)

summary(model)

lasso_coef <- model$beta |> as.matrix() |> as.data.frame() |> 
  rownames_to_column(var = "predictor") |> as_tibble()

lasso_coef_nonzero <- lasso_coef |> filter(s0 != 0)

lasso_coef_nonzero |> 
  ggplot() + geom_bar(aes(y = predictor, x = s0), stat = "identity")
```
